# Generated by Django 5.0.6 on 2024-06-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0007_alter_adminhod_id_alter_attendance_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=50),
        ),
        migrations.AddField(
            model_name='staffs',
            name='role',
            field=models.CharField(choices=[('Teacher', 'Teacher'), ('principal', 'Principal'), ('School_Manager', 'School_Manger'), ('Accountant', 'Accountant'), ('Librarian', 'Librarian')], default='Teacher', max_length=50),
        ),
    ]
